  services:
   nginx:
    image: quay.io/shesselink81/anna-nginx
    build: .
    restart: always
    ports:
      - "8090:80"
    user: "101:101"
    depends_on:
      - otel-collector

   otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml