{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    {{- include "annamaniacs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: otel-collector
  ports:
    - port: 4317
      targetPort: 4317
{{- end }}
