image:
  repository: quay.io/shesselink81/hesselinkme-nginx
  tag: v1.31.2
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

containerPort: 80

httproute:
  enabled: false
  hostnames:
    - example.com
  gateway:
    name: default-gateway
    namespace: default
  path:
    type: PathPrefix
    value: /

otelCollector:
  enabled: true
  image:
    repository: otel/opentelemetry-collector
    tag: latest
    pullPolicy: IfNotPresent
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    exporters:
      debug:
        verbosity: detailed
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug]