image:
  repository: quay.io/shesselink81/hesselinkme-nginx
  tag: v1.31.2
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

containerPort: 80

httproute:
  enabled: false
  hostnames:
    - example.com
  gateway:
    name: default-gateway
    namespace: default
  path:
    type: PathPrefix
    value: /

otelCollector:
  enabled: true
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: latest
    pullPolicy: IfNotPresent
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    connectors:
      span_metrics:
        histogram:
          explicit:
            buckets: [10ms, 50ms, 100ms, 250ms, 500ms, 1s, 5s]
        dimensions:
          - name: http.method
          - name: http.status_code
    exporters:
      debug:
        verbosity: detailed
      otlp_http/prometheus:
        endpoint: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090/api/v1/otlp
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, span_metrics]
        metrics:
          receivers: [span_metrics]
          exporters: [otlp_http/prometheus]